=== DanielReid/addis/schema/ADDIS-Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="addis-data">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="indications" type="Indications"/>
				<xs:element name="endpoints" type="Endpoints"/>
				<xs:element name="adverseEvents" type="AdverseEvents"/>
				<xs:element name="drugs" type="Drugs"/>
				<xs:element name="populationCharacteristics" type="PopulationCharacteristics"/>
				<xs:element name="studies" type="Studies"/>
				<xs:element name="metaAnalyses" type="MetaAnalyses"/>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="drugNameKey">
			<xs:selector xpath="drugs/drug"/>
			<xs:field xpath="@name"/>
		</xs:key>
		<xs:keyref name="armsdrugKeyRef" refer="drugNameKey">
			<xs:selector xpath="studies/study/arms/arm/drug"/>
			<xs:field xpath="@name"/>
		</xs:keyref>
		<xs:keyref name="pairwiseMetaAnalysesDrugNameKeyRef" refer="drugNameKey">
			<xs:selector xpath="metaAnalyses/pairwiseMetaAnalysis/alternative/drug"/>
			<xs:field xpath="@name"/>
		</xs:keyref>
		<xs:key name="indicationNameKey">
			<xs:selector xpath="indications/indication"/>
			<xs:field xpath="@name"/>
		</xs:key>
		<xs:keyref name="studyIndicationKeyRef" refer="indicationNameKey">
			<xs:selector xpath="studies/study/indication"/>
			<xs:field xpath="@name"/>
		</xs:keyref>
		<xs:keyref name="pairwiseMetaAnalysisIndicationKeyRef" refer="indicationNameKey">
			<xs:selector xpath="metaAnalyses/pairwiseMetaAnalysis/indication"/>
			<xs:field xpath="@name"/>
		</xs:keyref>
		<xs:key name="studyIdKey">
			<xs:selector xpath="studies/study"/>
			<xs:field xpath="@studyId"/>
		</xs:key>
		<xs:keyref name="pairwiseMetaAnalysesStudyIdDummy" refer="studyIdKey">
			<xs:selector xpath="metaAnalyses/pairwiseMetaAnalysis/alternative/arms/arm"/>
			<xs:field xpath="@study"/>
		</xs:keyref>
		<xs:key name="adverseEventNameKey">
			<xs:selector xpath="adverseEvents/adverseEvent"/>
			<xs:field xpath="@name"/>
		</xs:key>
		<xs:keyref name="studyAdverseEventKeyRef" refer="adverseEventNameKey">
			<xs:selector xpath="studies/study/adverseEvents/adverseEvent"/>
			<xs:field xpath="@name"/>
		</xs:keyref>
		<xs:keyref name="studyMeasurementsAdverseEventKeyRef" refer="adverseEventNameKey">
			<xs:selector xpath="studies/study/measurements/measurement/adverseEvent"/>
			<xs:field xpath="@name"/>
		</xs:keyref>
		<xs:keyref name="pairwiseMetaAnalysesAdverseEventKeyRef" refer="adverseEventNameKey">
			<xs:selector xpath="metaAnalyses/pairwiseMetaAnalysis/adverseEvent"/>
			<xs:field xpath="@name"/>
		</xs:keyref>
		<xs:key name="studyArmKey">
			<xs:selector xpath="studies/study/arms/arm"/>
			<xs:field xpath="@id"/>
		</xs:key>
		<xs:keyref name="PairwiseMetaAnalysisStudyArmKeyKeyRef" refer="studyArmKey">
			<xs:selector xpath="metaAnalyses/pairwiseMetaAnalysis/arms/arm"/>
			<xs:field xpath="@study"/>
		</xs:keyref>
		<xs:keyref name="NetworkMetaAnalysisStudyArmKeyKeyRef" refer="studyArmKey">
			<xs:selector xpath="metaAnalyses/networkMetaAnalysis/arms/arm"/>
			<xs:field xpath="@study"/>
		</xs:keyref>
		<xs:key name="endpointNameKey">
			<xs:selector xpath="endpoints/endpoint"/>
			<xs:field xpath="@name"/>
		</xs:key>
		<xs:keyref name="endpointInStudyKeyRef" refer="endpointNameKey">
			<xs:selector xpath="studies/study/endpoints/endpoint"/>
			<xs:field xpath="@name"/>
		</xs:keyref>
		<xs:key name="populationCharacteristicsNameKey">
			<xs:selector xpath="populationCharacteristics/populationCharacteristic"/>
			<xs:field xpath="@name"/>
		</xs:key>
		<xs:keyref name="populationCharacteristicsInStudyKeyRef" refer="populationCharacteristicsNameKey">
			<xs:selector xpath="studies/study/populationCharacteristics/populationCharacteristic"/>
			<xs:field xpath="@name"/>
		</xs:keyref>
		<xs:key name="armIdKey">
			<xs:selector xpath="studies/study/arms/arm"/>
			<xs:field xpath="@id"/>
		</xs:key>
		<xs:keyref name="studyMeasurementArmRef" refer="armIdKey">
			<xs:selector xpath="studies/study/measurements/measurement/arm"/>
			<xs:field xpath="@id"/>
		</xs:keyref>
	</xs:element>
	<xs:complexType name="Indications">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="indication" type="Indication"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Endpoints">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="endpoint" type="OutcomeMeasure"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AdverseEvents">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="adverseEvent" type="OutcomeMeasure"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Drugs">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="drug" type="Drug"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PopulationCharacteristics">
		<xs:sequence maxOccurs="unbounded" minOccurs="0">
			<xs:element name="populationCharacteristic" type="OutcomeMeasure"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Studies">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="study" type="Study"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MetaAnalyses">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:choice>
				<xs:element name="pairwiseMetaAnalysis" type="PairwiseMetaAnalysis"/>
				<xs:element name="networkMetaAnalysis" type="NetworkMetaAnalysis"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Indication">
		<xs:attribute name="code" type="xs:integer"/>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="OutcomeMeasure">
		<xs:choice>
			<xs:element name="continuous" type="ContinuousVariable"/>
			<xs:element name="rate" type="RateVariable"/>
			<xs:element name="categorical" type="CategoricalVariable"/>
		</xs:choice>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="description" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="ContinuousVariable">
		<xs:attribute name="direction" type="Direction"/>
		<xs:attribute name="unitOfMeasurement" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="RateVariable">
		<xs:attribute name="direction" type="Direction"/>
	</xs:complexType>
	<xs:complexType name="CategoricalVariable">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="category" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Drug">
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="atcCode" type="Alphanumeric"/>
	</xs:complexType>
	<xs:complexType name="Study">
		<xs:sequence>
			<xs:element name="indication" type="IndicationReference"/>
			<xs:element name="characteristics" type="Characteristics"/>
			<xs:element name="adverseEvents" type="AdverseEventReferences"/>
			<xs:element name="endpoints" type="EndpointReferences"/>
			<xs:element name="populationCharacteristics" type="PopulationCharacteristicReferences"/>
			<xs:element name="arms" type="Arms"/>
			<xs:element name="measurements" type="Measurements"/>
		</xs:sequence>
		<xs:attribute name="studyId" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="EndpointReferences">
		<xs:sequence maxOccurs="unbounded" minOccurs="0">
			<xs:element name="endpoint" type="EndpointReference"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PopulationCharacteristicReferences">
		<xs:sequence minOccurs="0">
			<xs:element name="populationCharacteristic" type="PopulationCharacteristicReference"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Measurements">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="measurement" type="Measurement"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Measurement">
		<xs:sequence>
			<xs:choice>
				<xs:element name="adverseEvent" type="AdverseEventReference"/>
				<xs:element name="endpoint" type="EndpointReference"/>
				<xs:element name="populationCharacteristic" type="PopulationCharacteristicReference"/>
			</xs:choice>
			<xs:element name="arm" type="ArmReference"/>
			<xs:choice>
				<xs:element name="rateMeasurement" type="RateMeasurement"/>
				<xs:element name="continuousMeasurement" type="ContinuousMeasurement"/>
				<xs:element name="categoricalMeasurement" type="CategoricalMeasurement"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="RateMeasurement">
		<xs:attribute name="rate" type="xs:integer"/>
		<xs:attribute name="sampleSize" type="xs:integer"/>
	</xs:complexType>
	<xs:complexType name="ContinuousMeasurement">
		<xs:attribute name="mean" type="xs:float"/>
		<xs:attribute name="sampleSize" type="xs:integer"/>
		<xs:attribute name="stdDev" type="xs:float"/>
	</xs:complexType>
	<xs:complexType name="CategoricalMeasurement">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="category" type="Category"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Category">
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="rate" type="xs:integer"/>
	</xs:complexType>
	
	<xs:complexType name="PairwiseMetaAnalysis">
		<xs:sequence>
			<xs:element name="indication" type="IndicationReference"/>
			<xs:choice>
				<xs:element name="adverseEvent" type="AdverseEventReference"/>
				<xs:element name="endpoint" type="EndpointReference"/>
			</xs:choice>
			<xs:sequence maxOccurs="2" minOccurs="2">
				<xs:element name="alternative" type="Alternative"/>
			</xs:sequence>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="NetworkMetaAnalysis">
		<xs:complexContent>
			<xs:extension base="PairwiseMetaAnalysis">
				<xs:sequence maxOccurs="unbounded" minOccurs="0">
					<xs:element name="alternative" type="Alternative"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Alternative">
		<xs:sequence>
			<xs:element name="drug" type="DrugReference"/>
			<xs:element name="arms" type="AnalysisArms"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AnalysisArms">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="arm" type="ArmReference"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AdverseEventReferences">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="adverseEvent" type="AdverseEventReference"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Characteristics">
		<xs:sequence>
			<xs:element name="title" type="xs:string"/>
			<xs:element default="UNKNOWN" minOccurs="0" name="allocation" type="Allocation"/>
			<xs:element default="UNKNOWN" minOccurs="0" name="blinding" type="Blinding"/>
			<xs:element minOccurs="0" name="centers" type="xs:integer"/>
			<xs:element minOccurs="0" name="objective" type="xs:string"/>
			<xs:element minOccurs="0" name="studyStart" type="xs:date"/>
			<xs:element minOccurs="0" name="studyEnd" type="xs:date"/>
			<xs:element default="UNKNOWN" minOccurs="0" name="status" type="Status"/>
<!-- check this, because there should always be a inclusion, exclusion and source -->
			<xs:element default="UNKNOWN" minOccurs="0" name="inclusion" type="xs:string"/>
			<xs:element default="UNKNOWN" minOccurs="0" name="exclusion" type="xs:string"/>
			<xs:element name="references" type="References"/>
			<xs:element default="MANUAL" minOccurs="0" name="source" type="Source"/>
			<xs:element minOccurs="0" name="creationDate" type="xs:date"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="References">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:choice>
				<xs:element name="pubMedId" type="xs:integer"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="Status">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NOT_YET_RECRUITING"/>
			<xs:enumeration value="RECRUITING"/>
			<xs:enumeration value="ENROLLING"/>
			<xs:enumeration value="ACTIVE"/>
			<xs:enumeration value="COMPLETED"/>
			<xs:enumeration value="SUSPENDED"/>
			<xs:enumeration value="TERMINATED"/>
			<xs:enumeration value="WITHDRAWN"/>
			<xs:enumeration value="UNKNOWN"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Blinding">
		<xs:restriction base="xs:string">
			<xs:enumeration value="OPEN"/>
			<xs:enumeration value="SINGLE_BLIND"/>
			<xs:enumeration value="DOUBLE_BLIND"/>
			<xs:enumeration value="TRIPLE_BLIND"/>
			<xs:enumeration value="UNKNOWN"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Source">
		<xs:restriction base="xs:string">
			<xs:enumeration value="MANUAL"/>
			<xs:enumeration value="CLINICALTRIALS"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Allocation">
		<xs:restriction base="xs:string">
			<xs:enumeration value="RANDOMIZED"/>
			<xs:enumeration value="NONRANDOMIZED"/>
			<xs:enumeration value="UNKNOWN"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Direction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="LOWER_IS_BETTER"/>
			<xs:enumeration value="HIGHER_IS_BETTER"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Alphanumeric">
		<xs:restriction base="xs:string">
			<xs:pattern value="([a-zA-Z0-9])*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="Arms">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="arm" type="Arm"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Arm">
		<xs:sequence>
			<xs:choice>
				<xs:element name="flexibleDose" type="FlexibleDose"/>
				<xs:element name="fixedDose" type="FixedDose"/>
			</xs:choice>
			<xs:element name="drug" type="DrugReference"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:integer"/>
		<xs:attribute name="size" type="xs:integer"/>
	</xs:complexType>
	<xs:complexType name="FlexibleDose">
		<xs:attribute name="minDose" type="xs:float"/>
		<xs:attribute name="maxDose" type="xs:float"/>
		<xs:attribute name="unit" type="Unit"/>
	</xs:complexType>
	<xs:complexType name="FixedDose">
		<xs:attribute name="quantity" type="xs:float"/>
		<xs:attribute name="unit" type="Unit"/>
	</xs:complexType>
	<xs:simpleType name="Unit">
		<xs:restriction base="xs:string">
			<xs:enumeration value="MILLIGRAMS_A_DAY"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="DrugReference">
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="IndicationReference">
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="AdverseEventReference">
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="EndpointReference">
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="StudyReference">
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="ArmReference">
		<xs:attribute name="id" type="xs:integer"/>
		<xs:attribute name="study" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="PopulationCharacteristicReference">
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
</xs:schema>

=== DanielReid/addis/schema/schematestxml.xml
<addis-data xsi:noNamespaceSchemaLocation="./ADDIS-Schema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<indications>
		<indication code="130" name="Erectile Dysfunction"/>
		<indication code="2709" name="Eating Disorder"/>
	</indications>
	<endpoints>
		<endpoint name="CGI Severity Change" description="Change from baseline CGI Severity of Illness score">
			<continuous direction="HIGHER_IS_BETTER" unitOfMeasurement="Deviation from the baseline of CGI Severity of Illness score"/>
		</endpoint>
		<endpoint name="Dropouts" description="Number of patients dropping out of the study prematurely">
			<rate direction="LOWER_IS_BETTER"/>
		</endpoint>
	</endpoints>
	<adverseEvents>
		<adverseEvent name="Abdominal Pain" description="">
			<rate direction="LOWER_IS_BETTER"/>
		</adverseEvent>
		<adverseEvent name="Increased Duration Of Sleep" description="">
			<rate direction="LOWER_IS_BETTER"/>
		</adverseEvent>
	</adverseEvents>
	<drugs>
		<drug name="Fluoxetine" atcCode="N013423"/>
		<drug name="Paroxetine" atcCode="N0134233"/>
	</drugs>
	<populationCharacteristics>
		<populationCharacteristic name="Gender" description="WHICH ONE IS IT">
			<categorical>
				<category>MALE</category>
				<category>FEMALE</category>
			</categorical>
		</populationCharacteristic>
	</populationCharacteristics>
	<studies>
		<study>
			<indication name="Erectile Dysfunction"/>
			<characteristics>
				<title>Sertraline versus paroxetine in major depression: clinical outcome after six months of continuous therapy</title>
				<allocation>RANDOMIZED</allocation>
				<blinding>DOUBLE_BLIND</blinding>
				<objective>Relatively little research is available comparing the efficacy and tolerability of selective serotonin reuptake inhibitors (SSRIs) during continuation therapy. This investigation reports the differential effect of 6 months of treatment with sertraline versus paroxetine for symptoms of depression, quality of life, and personality outcomes.</objective>
				<status>COMPLETED</status>
				<inclusion>The subjects were male and female outpatients, aged 18 years and older, who met DSM-III-R criteria for major depression and who had a 10-item Montgomery-Ã…sberg Depression Rating Scale (MADRS)9  score of 21 or more at baseline,      with less than 25% improvement on the MADRS during the washout period. Enrollment of fertile women was contingent upon a negative      result on a pregnancy test and stable use for 3 months of medically accepted contraception before study entry.</inclusion>
				<exclusion>(1) current or past history of mania or hypomania, alcoholism or substance abuse, dementia, or epilepsy; (2) presence of psychotic depression or organic affective illness; (3) history of suicide attempts or current high suicide risk (&gt;4 on item 10 of the MADRS); (4) current use of any psychotropic medication, except for the use of one of three hypnotic/anxiolytic medications (nitrazepam [2.5-10 mg], flunitrazepam [0.5-2 mg], or oxazepam [15-25 mg]); (5) treatment with lithium in the month prior to the screening or with a monoamine oxidase inhibitor in the 2 weeks before the screening; (6) a history of significant intolerance or allergic reaction to sertraline or paroxetine; and (7) evidence of clinically significant hepatic or renal disease, any other acute or unstable medical condition, or use of any concomitant medication that might interfere with the safe conduct of the study.</exclusion>
				<references>
					<pubMedId>11106136</pubMedId>
					<pubMedId>11106138</pubMedId>
				</references>
			</characteristics>
			<adverseEvents>
				<adverseEvent name="Abdominal Pain"/>
				<adverseEvent name="Increased Duration Of Sleep"/>
			</adverseEvents>
			<arms>
				<arm id="76" size="177">
					<flexibleDose maxDose="40.0" minDose="20.0" unit="MILLIGRAMS_A_DAY"/>
					<drug name="Fluoxetine"/>
				</arm>
				<arm id="77" size="176">
					<fixedDose quantity="50.0" unit="MILLIGRAMS_A_DAY"/>
					<drug name="Paroxetine"/>
				</arm>
			</arms>
		</study>
	</studies>
</addis-data>
